# @link https://www.jenkins.io/doc/book/installing/docker/
# @link https://github.com/jenkinsci/docker
version: '3.2'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "12801:8080"
    expose:
      - "50000"
    volumes:
      - ./data:/var/jenkins_home
      #- /usr/bin/docker:/usr/bin/docker
      #- /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Asia/Shanghai
    privileged: true
    user: root
    restart: always
    environment:
      JAVA_OPTS: '-Djava.util.logging.config.file=/var/jenkins_home/log.properties'
