# @link https://github.com/dani-garcia/bitwarden_rs
version: '3.2'

services:
  bitwardenrs:
    image: bitwardenrs/server
    container_name: bitwarden
    ports:
      - "8189:80"
    volumes:
      - ./data:/data
    restart: always
